// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5YwHExy83vQAcxrXyVnAQJXAQ0ngWccY',
    appId: '1:115260365576:web:b957fd5e6654b17d14eabd',
    messagingSenderId: '115260365576',
    projectId: 'self-chat-6086d',
    authDomain: 'self-chat-6086d.firebaseapp.com',
    storageBucket: 'self-chat-6086d.appspot.com',
    measurementId: 'G-BVDZY7VYR1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZdN6a-w6Xxkb3Eri38ybPTv3-xv0NHJ8',
    appId: '1:115260365576:android:5ae1049243dd560814eabd',
    messagingSenderId: '115260365576',
    projectId: 'self-chat-6086d',
    storageBucket: 'self-chat-6086d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdLb6KeP363_jJUgDZzz08jsBARFgmA78',
    appId: '1:115260365576:ios:4aaf010653327d6f14eabd',
    messagingSenderId: '115260365576',
    projectId: 'self-chat-6086d',
    storageBucket: 'self-chat-6086d.appspot.com',
    iosBundleId: 'com.example.selfChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdLb6KeP363_jJUgDZzz08jsBARFgmA78',
    appId: '1:115260365576:ios:4aaf010653327d6f14eabd',
    messagingSenderId: '115260365576',
    projectId: 'self-chat-6086d',
    storageBucket: 'self-chat-6086d.appspot.com',
    iosBundleId: 'com.example.selfChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5YwHExy83vQAcxrXyVnAQJXAQ0ngWccY',
    appId: '1:115260365576:web:8b7318b49277996914eabd',
    messagingSenderId: '115260365576',
    projectId: 'self-chat-6086d',
    authDomain: 'self-chat-6086d.firebaseapp.com',
    storageBucket: 'self-chat-6086d.appspot.com',
    measurementId: 'G-M42NNSJYLH',
  );
}
